### ISSUE TITLE
Cluster Abell 119

### ISSUE THREAD

**Issue by gabriel-fontinele** [tomasplsek/CADET#1]
Hi, could you help me use CADET for the Abell 119 cluster? What treatment should I undergo during observation to be able to use CADET? Has it already been implemented to detect shock fronts and sloshing?

**Comment by gabriel-fontinele** [comment]
Another question: can the cadet identify the inflated cavities even when I have a sloshing spiral?

**Comment by tomasplsek** [comment]
> Hi, could you help me use CADET for the Abell 119 cluster? What treatment should I undergo during observation to be able to use CADET? Has it already been implemented to detect shock fronts and sloshing?

Hi Gabriel, it should be possible to apply CADET to both flux images obtained by running the fluximage/flux_obs CIAO procedure as well as to raw merged images with units of counts.

It is usually also recommended to fill in the point sources using the dmfilth CIAO procedure, but for clusters, this is often not necessary, since there are very few of them compared to nearby early-type galaxies.

Regarding the shock fronts and sloshing: this was meant mainly to be implemented in the future training data so that the model learns to ignore them and does not produce false-positive predictions for sources with significant shock and sloshing features. The network itself, however, was not built to detect these features.

**Comment by tomasplsek** [comment]
> Another question: can the cadet identify the inflated cavities even when I have a sloshing spiral? 

Yes, CADET should give quite good predicitions even for sources afected by sloshing, but the reliability of predictions strongly depends on the prominence of the sloshing effect - if the sloshing spiral is the dominant feature on the image, the predictions will probably be prone to false-positives.

**Comment by gabriel-fontinele** [comment]
Could you test for me with Abell 119, obsid 7918? I haven't been able to use it yet.

**Comment by tomasplsek** [comment]
Okay, I downloaded both Chandra OBSIDs for Abell 119 (4180,7918), merged them with merge_obs, filled in point sources using dmfilth, and applied CADET on it. I can send you the resulting images and data products if you'd want them (just leave me a contact address or send me an email).

The problem with this particular cluster is that it's quite hot (>5 keV) and doesn't have a cool core, which leads to the fact that it appears very extended (it's also big & nearby) and it does not fully fit into Chandra ACIS-I chips. This could be problematic for CADET, because if you'd want to detect cavities on very big scales comparable to the size of the chip, the dark areas behind chip edges might confuse CADET and it might produce false positive predictions. Using an XMM-Newton observation (if existent) instead of Chandra might help, but then all the small features would be blurred out.

So I applied CADET on the largest possible scales (8,9,10,11,12,13) and got the output attached below. I also decreased the thresholds to 0.3 and 0.5, because most of the detections had a rather lower significance. Nevertheless, after that, CADET found two possible cavity candidates and detected them on multiple size-scales which is a good sign. In order to show the significance of detected cavities, I would however recommend you to take similar approach as I did in my [CADET paper](https://academic.oup.com/mnras/article/527/2/3315/7339785) and produce azimuthal profiles to show how significant the brightness drops actually are. And fitting the image with a beta model (for instance using my [interactive tool](https://github.com/tomasplsek/Beta-modelling) ;)) and visually detecting the cavities on the residual image could also help. 

I would however be very cautious with claiming these candidates as confirmed cavities, since the cluster Abell 119 seems quite dynamically active (e.g. [Watson et al. 2023](https://arxiv.org/abs/2308.04367v2)) and also because the upper cavity can possibly also be a false positive due to the chip gap. 

![A119_CADETv3](https://github.com/tomasplsek/CADET/assets/34679051/7dcee16c-f31a-4d45-9673-fd0bdd5adfd5)
